version: '1.0'
stages:
  - prepare
  - build
  - push
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'nasirhm/learning-sonar-java'
    revision: main
    git: github
#  BuildingDockerImage:
#    title: Building Docker Image
#    stage: build
#    type: build
#    image_name: learning-sonar-java
#    working_directory: ./
#    tag: 'multi-stage'
#    dockerfile: Dockerfile
  BuildApplication:
    title: Building Application with Gradle
    stage: build
    type: freestyle
    image: gradle:6.8.2-jdk15
    commands:
      - 'gradle build'
  PrintFileList:
    title: 'Listing files'
    image: alpine:latest
    commands:
      - 'ls -l'
      - 'pwd'
  sonarqube:
    type: "sonar-scanner-cli"
    stage: "push"
    arguments:
      SONAR_HOST_URL: 'https://sonarcloud.io' # replace with your host url
      SONAR_LOGIN: "${{SONAR_TOKEN}}" # replace with your access token
      SONAR_PROJECT_BASE_DIR: "/codefresh/volume/${{CF_REPO_NAME}}" #replace with your working directory
      SONAR_SCANNER_CLI_VERSION: "latest"
  nexus:
    title: 'Publishing the Artifact'
    type: "freestyle"
    stage: "push"
    image: gradle:6.8.2-jdk15
    commands:
      - 'gradle ArtifactoryPublish -Partifactory_user=${{ARTIFACTORY_USERNAME}} -Partifactory_password=${{ARTIFACTORY_PASSWORD}} -Partifactory_url=${{ARTIFACTORY_URL}}'