version: '1.0'
stages:
  - prepare
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'nasirhm/learning-sonar-java'
    revision: main
    git: github
  BuildingDockerImage:
    title: Building Docker Image
    stage: build
    type: build
    image_name: learning-sonar-java
    working_directory: ./
    tag: 'multi-stage'
    dockerfile: Dockerfile
  sonarqube:
    type: "sonar-scanner-cli"
    stage: "push"
    arguments:
      SONAR_HOST_URL: 'https://sonarcloud.io/' # replace with your host url
      SONAR_LOGIN: "${{SONAR_TOKEN}}" # replace with your access token
      SONAR_PROJECT_BASE_DIR: "/codefresh/volume/sonarqube-example" #replace with your working directory
      SONAR_SCANNER_CLI_VERSION: "latest"